In [79]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.cluster import KMeans

from sklearn.metrics import silhouette_score

In [80]:
df = pd.read_csv("customers.csv")

In [81]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [82]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [83]:
df.duplicated().sum()

np.int64(0)

In [84]:
df = df.drop_duplicates()

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3499 entries, 0 to 3498
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        3499 non-null   object
 1   gender            3499 non-null   object
 2   SeniorCitizen     3499 non-null   int64
 3   Partner           3499 non-null   object
 4   Dependents        3499 non-null   object
 5   tenure            3499 non-null   int64
 6   PhoneService      3499 non-null   object
 7   MultipleLines     3499 non-null   object
 8   InternetService   3499 non-null   object
 9   OnlineSecurity    3499 non-null   object
 10  OnlineBackup      3499 non-null   object
 11  DeviceProtection  3499 non-null   object
 12  TechSupport       3499 non-null   object
 13  StreamingTV       3499 non-null   object
 14  StreamingMovies   3499 non-null   object
 15  Contract          3499 non-null   object
 16  PaperlessBilling  3499 non-null   object
 17  PaymentMethod     3499 non-null   object
 18  MonthlyCharges    3499 non-null   float64
 19  TotalCharges      3499 non-null   object
 20  Churn             3499 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 574.2+ KB

In [86]:
print("Rows and Columns:", df.shape)

Rows and Columns: (3499, 21)

In [87]:
df.drop(columns=["customerID", "Churn"], inplace=True)

In [88]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3499 entries, 0 to 3498
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            3499 non-null   int64
 1   SeniorCitizen     3499 non-null   int64
 2   Partner           3499 non-null   int64
 3   Dependents        3499 non-null   int64
 4   tenure            3499 non-null   int64
 5   PhoneService      3499 non-null   int64
 6   MultipleLines     3499 non-null   int64
 7   InternetService   3499 non-null   int64
 8   OnlineSecurity    3499 non-null   int64
 9   OnlineBackup      3499 non-null   int64
 10  DeviceProtection  3499 non-null   int64
 11  TechSupport       3499 non-null   int64
 12  StreamingTV       3499 non-null   int64
 13  StreamingMovies   3499 non-null   int64
 14  Contract          3499 non-null   int64
 15  PaperlessBilling  3499 non-null   int64
 16  PaymentMethod     3499 non-null   int64
 17  MonthlyCharges    3499 non-null   float64
 18  TotalCharges      3499 non-null   int64
dtypes: float64(1), int64(18)
memory usage: 519.5 KB

In [90]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,1301
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,770
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,84
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,733
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,479

In [91]:
df.tail()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
3494,0,0,1,1,9,1,2,1,0,0,0,0,2,0,0,1,0,85.35,2985
3495,1,1,0,0,1,1,2,1,0,0,0,0,0,0,0,1,2,75.35,2971
3496,1,0,0,0,25,1,0,1,2,0,0,0,0,0,0,0,0,74.30,824
3497,0,1,1,0,2,1,0,1,0,0,0,0,0,0,0,1,2,69.30,497
3498,1,0,0,0,43,1,0,1,2,0,0,0,0,0,0,1,2,75.20,1435

In [92]:
df.shape

(3499, 19)

In [93]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df)

In [94]:
print(X_scaled[:5])

[[-1.0175882  -0.43279225  1.03520048 -0.66281625 -1.26914941 -3.17376508
   0.06395517 -1.19116612 -0.91903303  1.24269649 -1.0337682  -0.92058093
  -1.11381712 -1.14020611 -0.83008381  0.83135741  0.4059484  -1.16996092
  -0.38365536]
 [ 0.9827158  -0.43279225 -0.96599647 -0.66281625  0.07281205  0.31508318
  -0.9866512  -1.19116612  1.40865178 -1.03086953  1.23902787 -0.92058093
  -1.11381712 -1.14020611  0.36862162 -1.20285209  1.34104613 -0.2685803
  -0.93062305]
 [ 0.9827158  -0.43279225 -0.96599647 -0.66281625 -1.22848391  0.31508318
  -0.9866512  -1.19116612  1.40865178  1.24269649 -1.0337682  -0.92058093
  -1.11381712 -1.14020611 -0.83008381  0.83135741  1.34104613 -0.37169026
  -1.63725173]
 [ 0.9827158  -0.43279225 -0.96599647 -0.66281625  0.52013253 -3.17376508
   0.06395517 -1.19116612  1.40865178 -1.03086953  1.23902787  1.4059721
  -1.11381712 -1.14020611  0.36862162 -1.20285209 -1.46424706 -0.75585802
  -0.96873567]
 [-1.0175882  -0.43279225 -0.96599647 -0.66281625 -1.22848391  0.31508318
  -0.9866512   0.16645286 -0.91903303 -1.03086953 -1.0337682  -0.92058093
  -1.11381712 -1.14020611 -0.83008381  0.83135741  0.4059484   0.18876226
  -1.2303737 ]]

In [95]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

In [96]:
print(X_pca.shape)

(3499, 2)

In [97]:
print("Explained Variance Ratio:", pca.explained_variance_ratio_)

Explained Variance Ratio: [0.18852077 0.12029406]

In [98]:
print("Total Variance Explained:", pca.explained_variance_ratio_.sum())

Total Variance Explained: 0.30881482662341797

In [99]:
from sklearn.cluster import KMeans

In [100]:
wcss = []

for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X_pca)
    wcss.append(kmeans.inertia_)

In [101]:
for i, value in enumerate(wcss, start=2):
    print(f"Clusters = {i}, WCSS = {value:.2f}")

Clusters = 2, WCSS = 11782.84
Clusters = 3, WCSS = 7253.56
Clusters = 4, WCSS = 5398.10
Clusters = 5, WCSS = 4318.82
Clusters = 6, WCSS = 3628.75
Clusters = 7, WCSS = 3114.72
Clusters = 8, WCSS = 2727.99
Clusters = 9, WCSS = 2457.19
Clusters = 10, WCSS = 2240.10

In [102]:
from sklearn.metrics import silhouette_score

In [103]:
silhouette_scores = []

for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca)

    score = silhouette_score(X_pca, labels)
    silhouette_scores.append(score)

    print(f"Clusters = {i}, Silhouette Score = {score:.4f}")

Clusters = 2, Silhouette Score = 0.3848
Clusters = 3, Silhouette Score = 0.4113
Clusters = 4, Silhouette Score = 0.3857
Clusters = 5, Silhouette Score = 0.3730
Clusters = 6, Silhouette Score = 0.3572
Clusters = 7, Silhouette Score = 0.3667
Clusters = 8, Silhouette Score = 0.3640
Clusters = 9, Silhouette Score = 0.3520
Clusters = 10, Silhouette Score = 0.3492

In [104]:
best_k = silhouette_scores.index(max(silhouette_scores)) + 2

print("Best Number of Clusters:", best_k)
print("Highest Silhouette Score:", max(silhouette_scores))

Best Number of Clusters: 3
Highest Silhouette Score: 0.4112601005316567

In [105]:
best_k = 3

kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)

clusters = kmeans.fit_predict(X_pca)

In [106]:
df["Cluster"] = clusters

In [107]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Cluster
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,1301,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,770,1
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,84,0
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,733,1
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,479,0

In [108]:
df["Cluster"].value_counts()

Cluster
0    1451
1    1059
2     989
Name: count, dtype: int64

In [109]:
df.to_csv("Customer_Segmentation_Result.csv", index=False)

In [110]:
cluster_summary = df.groupby("Cluster").mean()

cluster_summary

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
Cluster,,,,,,,,,,,,,,,,,,,
0,0.514817,0.237078,0.270848,0.124052,14.924190,0.898001,0.846313,0.667815,0.321158,0.500345,0.454859,0.315644,0.678153,0.719504,0.053067,0.738801,1.806340,68.932633,1573.350103
1,0.511804,0.012276,0.549575,0.488196,33.372049,0.895184,0.484419,1.380548,1.152030,0.993390,0.982059,1.070822,0.813975,0.817753,1.073654,0.255902,1.756374,34.192351,1323.704438
2,0.496461,0.197169,0.721941,0.375126,56.324570,0.942366,1.562184,0.646107,1.088979,1.410516,1.499494,1.190091,1.618807,1.637007,1.222447,0.734075,1.009100,92.306421,2194.829120

In [111]:
df["Cluster"].value_counts().sort_index()

Cluster
0    1451
1    1059
2     989
Name: count, dtype: int64

In [112]:
print(cluster_summary)

           gender  SeniorCitizen   Partner  Dependents     tenure  \
Cluster
0        0.514817       0.237078  0.270848    0.124052  14.924190
1        0.511804       0.012276  0.549575    0.488196  33.372049
2        0.496461       0.197169  0.721941    0.375126  56.324570

         PhoneService  MultipleLines  InternetService  OnlineSecurity  \
Cluster
0            0.898001       0.846313         0.667815        0.321158
1            0.895184       0.484419         1.380548        1.152030
2            0.942366       1.562184         0.646107        1.088979

         OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
Cluster
0            0.500345          0.454859     0.315644     0.678153
1            0.993390          0.982059     1.070822     0.813975
2            1.410516          1.499494     1.190091     1.618807

         StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
Cluster
0               0.719504  0.053067          0.738801       1.806340
1               0.817753  1.073654          0.255902       1.756374
2               1.637007  1.222447          0.734075       1.009100

         MonthlyCharges  TotalCharges
Cluster
0             68.932633   1573.350103
1             34.192351   1323.704438
2             92.306421   2194.829120

In [113]:
df.to_csv("Customer_Segmentation_Final.csv", index=False)